NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [ ]:
import numpy as np
print("Number of dimensions in sales_data:", sales_data.ndim)
print("Shape of sales_data:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type of the array:", sales_data.dtype)
print("Memory occupied by the array:", sales_data.nbytes, "bytes")

Number of dimensions in sales_data: 2
Shape of sales_data: (5, 6)
Total number of values: 30
Data type of the array: int64
Memory occupied by the array: 240 bytes


Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [ ]:
import numpy as np
print("Total number of stores:", len(stores))
print("Total number of product categories:", len(categories))
print("Total number of store-category combinations:", len(stores) * len(categories))

Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [ ]:
import numpy as np
sales_data_float32 = sales_data.astype(np.float32)
sales_data_float64 = sales_data.astype(np.float64)
print("Memory used by sales_data_float32:", sales_data_float32.nbytes, "bytes")
print("Memory used by sales_data_float64:", sales_data_float64.nbytes, "bytes")



Memory used by sales_data_float32: 120 bytes
Memory used by sales_data_float64: 240 bytes


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.



In [ ]:
import numpy as np
bengaluru_sales = sales_data[0, :]
print("Sales for Bengaluru:")
print(bengaluru_sales)


Sales for Bengaluru:
[850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories

In [ ]:
import numpy as np
mumbai_sales = sales_data[3, :]
mumbai_cost = cost_data[3, :]
total_cost_mumbai = np.sum(mumbai_cost)
print("Total cost incurred by Mumbai store for all product categories:")
print(total_cost_mumbai)


Total cost incurred by Mumbai store for all product categories:
2065000


Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.



In [ ]:
import numpy as np
electronics_sales = sales_data[:, 0]
print("Electronics sales for all stores:")
print(electronics_sales)


Electronics sales for all stores:
[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from cost_data.

In [ ]:
import numpy as np
clothing_cost = cost_data[:, 2]
print("Clothing cost for every store:")
print(clothing_cost)

Clothing cost for every store:
[220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [ ]:
import numpy as np
hyderabad_sales = sales_data[1, 3]
hyderabad_cost = cost_data[1, 3]
hyderabad_profit = hyderabad_sales - hyderabad_cost
print("Furniture sales in Hyderabad:", hyderabad_sales)
print("Furniture cost in Hyderabad:", hyderabad_cost)
print("Furniture profit in Hyderabad:", hyderabad_profit)

Furniture sales in Hyderabad: 310000
Furniture cost in Hyderabad: 225000
Furniture profit in Hyderabad: 85000


Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [ ]:
import numpy as np
chennai_sales = sales_data[2, 1:4]
print("Sales for Chennai in Groceries, Clothing, and Furniture:")
print(chennai_sales)


Sales for Chennai in Groceries, Clothing, and Furniture:
[390000 340000 260000]


Question 10: Selected Store Analysis

Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [ ]:
import numpy as np
selected_stores =["Bengaluru", "Chennai", "Pune"]
selected_categories = ["Electronics", "Clothing", "Beauty"]
selected_data = sales_data[np.isin(stores, selected_stores), np.isin(categories, selected_categories)]
print("Selected store and category data:")
print(selected_data)

Selected store and category data:
[850000 340000 175000]


Part 4: Sales Aggregation

Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
import numpy as np
total_sales = np.sum(sales_data)
print("Total sales revenue generated by all stores and all categories:", total_sales)


Total sales revenue generated by all stores and all categories: 11675000


Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

In [ ]:
import numpy as np
total_sales_per_store = np.sum(sales_data, axis=1)
for store, sales in zip(stores, total_sales_per_store):
    print(f"Store: {store}, Total Sales: {sales}")


Store: Bengaluru, Total Sales: 2270000
Store: Hyderabad, Total Sales: 2295000
Store: Chennai, Total Sales: 2310000
Store: Mumbai, Total Sales: 2820000
Store: Pune, Total Sales: 1980000


Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:
import numpy as np
total_sales_per_category = np.sum(sales_data, axis=0)
for category, sales in zip(categories, total_sales_per_category):
    print(f"Category: {category}, Total Sales: {sales}")


Category: Electronics, Total Sales: 4290000
Category: Groceries, Total Sales: 2185000
Category: Clothing, Total Sales: 1600000
Category: Furniture, Total Sales: 1415000
Category: Beauty, Total Sales: 1010000
Category: Sports, Total Sales: 1175000


Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
import numpy as np
average_sales_per_store = np.mean(sales_data, axis=1)
for store, average_sales in zip(stores, average_sales_per_store):
    print(f"Store: {store}, Average Sales: {average_sales}")

Store: Bengaluru, Average Sales: 378333.3333333333
Store: Hyderabad, Average Sales: 382500.0
Store: Chennai, Average Sales: 385000.0
Store: Mumbai, Average Sales: 470000.0
Store: Pune, Average Sales: 330000.0


Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.



In [ ]:
import numpy as np
average_sales_per_category = np.mean(sales_data, axis=0)
for category, average_sales in zip(categories, average_sales_per_category):
    print(f"Category: {category}, Average Sales: {average_sales}")

Category: Electronics, Average Sales: 858000.0
Category: Groceries, Average Sales: 437000.0
Category: Clothing, Average Sales: 320000.0
Category: Furniture, Average Sales: 283000.0
Category: Beauty, Average Sales: 202000.0
Category: Sports, Average Sales: 235000.0


Question 16: Highest-Selling Store

Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [ ]:
import numpy as np
highest_sales_index = np.argmax(total_sales_per_store)
highest_sales_store = stores[highest_sales_index]
highest_sales_value = total_sales_per_store[highest_sales_index]
print("Index of the store with the highest total sales:", highest_sales_index)
print("Name of the store with the highest total sales:", highest_sales_store)
print("Total sales generated by the store with the highest total sales:", highest_sales_value)

Index of the store with the highest total sales: 3
Name of the store with the highest total sales: Mumbai
Total sales generated by the store with the highest total sales: 2820000


Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use np.argmin()

In [ ]:
import numpy as np
lowest_sales_index = np.argmin(total_sales_per_store)
lowest_sales_store = stores[lowest_sales_index]
lowest_sales_value = total_sales_per_store[lowest_sales_index]
print("Index of the store with the lowest total sales:", lowest_sales_index)
print("Name of the store with the lowest total sales:", lowest_sales_store)
print("Total sales generated by the store with the lowest total sales:", lowest_sales_value)

Index of the store with the lowest total sales: 4
Name of the store with the lowest total sales: Pune
Total sales generated by the store with the lowest total sales: 1980000


Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [ ]:
import numpy as np
highest_sales_category_index = np.argmax(total_sales_per_category)
highest_sales_category = categories[highest_sales_category_index]
highest_sales_value = total_sales_per_category[highest_sales_category_index]
print("Category with the highest total sales:", highest_sales_category)
print("Total sales generated by the category:", highest_sales_value)


Category with the highest total sales: Electronics
Total sales generated by the category: 4290000


Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [ ]:
import numpy as np
lowest_sales_category_index = np.argmin(total_sales_per_category)
lowest_sales_category = categories[lowest_sales_category_index]
lowest_sales_value = total_sales_per_category[lowest_sales_category_index]
print("Category with the lowest total sales:", lowest_sales_category)
print("Total sales generated by the category:", lowest_sales_value)

Category with the lowest total sales: Beauty
Total sales generated by the category: 1010000


Part 5: Cost Analysis

Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
import numpy as np
total_cost = np.sum(cost_data)
print("Total cost incurred by SmartMart across all stores and product categories:", total_cost)

Total cost incurred by SmartMart across all stores and product categories: 8600000


Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [ ]:
import numpy as np
total_cost_per_store = np.sum(cost_data, axis=1)
for store, cost in zip(stores, total_cost_per_store):
    print(f"Store: {store}, Total Cost: {cost}")

Store: Bengaluru, Total Cost: 1665000
Store: Hyderabad, Total Cost: 1685000
Store: Chennai, Total Cost: 1710000
Store: Mumbai, Total Cost: 2065000
Store: Pune, Total Cost: 1475000


Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [ ]:
import numpy as np
total_cost_per_category = np.sum(cost_data, axis=0)
for category, cost in zip(categories, total_cost_per_category):
    print(f"Category: {category}, Total Cost: {cost}")

Category: Electronics, Total Cost: 3250000
Category: Groceries, Total Cost: 1660000
Category: Clothing, Total Cost: 1145000
Category: Furniture, Total Cost: 1045000
Category: Beauty, Total Cost: 665000
Category: Sports, Total Cost: 835000


Question 23: Most Expensive Store

Identify the store with the highest total operating cost

In [ ]:
import numpy as np
most_expensive_store_index = np.argmax(total_cost_per_store)
most_expensive_store = stores[most_expensive_store_index]
most_expensive_cost = total_cost_per_store[most_expensive_store_index]
print("Store with the highest total operating cost:", most_expensive_store)
print("Total operating cost of the store:", most_expensive_cost)

Store with the highest total operating cost: Mumbai
Total operating cost of the store: 2065000


Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [ ]:
import numpy as np
lowest_sales_category_index = np.argmin(total_sales_per_category)
lowest_sales_category = categories[lowest_sales_category_index]
lowest_sales_value = total_sales_per_category[lowest_sales_category_index]
print("Category with the lowest total sales:", lowest_sales_category)
print("Total sales generated by the category:", lowest_sales_value)

Category with the lowest total sales: Beauty
Total sales generated by the category: 1010000


Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [ ]:
import numpy as np
most_expensive_category_index = np.argmax(total_cost_per_category)
most_expensive_category = categories[most_expensive_category_index]
most_expensive_cost = total_cost_per_category[most_expensive_category_index]
print("Category with the highest total operating cost:", most_expensive_category)
print("Total operating cost of the category:", most_expensive_cost)

Category with the highest total operating cost: Electronics
Total operating cost of the category: 3250000


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [ ]:
import numpy as np
profit_data = sales_data - cost_data
print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit

Calculate the total profit generated by each store

In [ ]:
import numpy as np
total_profit_per_store = np.sum(profit_data, axis=1)
for store, profit in zip(stores, total_profit_per_store):
    print(f"Store: {store}, Total Profit: {profit}")

Store: Bengaluru, Total Profit: 605000
Store: Hyderabad, Total Profit: 610000
Store: Chennai, Total Profit: 600000
Store: Mumbai, Total Profit: 755000
Store: Pune, Total Profit: 505000


Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.



In [ ]:
import numpy as np
total_profit_per_category = np.sum(profit_data, axis=0)
for category, profit in zip(categories, total_profit_per_category):
    print(f"Category: {category}, Total Profit: {profit}")

Category: Electronics, Total Profit: 1040000
Category: Groceries, Total Profit: 525000
Category: Clothing, Total Profit: 455000
Category: Furniture, Total Profit: 370000
Category: Beauty, Total Profit: 345000
Category: Sports, Total Profit: 340000


Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [ ]:
import numpy as np
most_profitable_store_index = np.argmax(total_profit_per_store)
most_profitable_store = stores[most_profitable_store_index]
total_sales_most_profitable_store = total_sales_per_store[most_profitable_store_index]
total_cost_most_profitable_store = total_cost_per_store[most_profitable_store_index]
total_profit_most_profitable_store = total_profit_per_store[most_profitable_store_index]
print("Store with the highest total profit:")
print(f"Store Name: {most_profitable_store}")
print(f"Total Sales: {total_sales_most_profitable_store}")

Store with the highest total profit:
Store Name: Mumbai
Total Sales: 2820000


Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [ ]:
import numpy as np
least_profitable_store_index = np.argmin(total_profit_per_store)
least_profitable_store = stores[least_profitable_store_index]
total_sales_least_profitable_store = total_sales_per_store[least_profitable_store_index]
total_cost_least_profitable_store = total_cost_per_store[least_profitable_store_index]
total_profit_least_profitable_store = total_profit_per_store[least_profitable_store_index]
print("Store with the lowest total profit:")
print(f"Store Name: {least_profitable_store}")
print(f"Total Sales: {total_sales_least_profitable_store}")

Store with the lowest total profit:
Store Name: Pune
Total Sales: 1980000


Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.



In [ ]:
import numpy as np
most_profitable_category_index = np.argmax(total_profit_per_category)
most_profitable_category = categories[most_profitable_category_index]
total_sales_most_profitable_category = total_sales_per_category[most_profitable_category_index]
total_cost_most_profitable_category = total_cost_per_category[most_profitable_category_index]
total_profit_most_profitable_category = total_profit_per_category[most_profitable_category_index]
print("Category with the highest total profit:")
print(f"Category Name: {most_profitable_category}")
print(f"Total Sales: {total_sales_most_profitable_category}")

Category with the highest total profit:
Category Name: Electronics
Total Sales: 4290000


Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [ ]:
import numpy as np
least_profitable_category_index = np.argmin(total_profit_per_category)
least_profitable_category = categories[least_profitable_category_index]
total_sales_least_profitable_category = total_sales_per_category[least_profitable_category_index]
total_cost_least_profitable_category = total_cost_per_category[least_profitable_category_index]
total_profit_least_profitable_category = total_profit_per_category[least_profitable_category_index]
print("Category with the lowest total profit:")
print(f"Category Name: {least_profitable_category}")
print(f"Total Sales: {total_sales_least_profitable_category}")

Category with the lowest total profit:
Category Name: Sports
Total Sales: 1175000


Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [ ]:
import numpy as np
max_profit_index = np.unravel_index(np.argmax(profit_data), profit_data.shape)
max_profit = profit_data[max_profit_index]
max_profit_store = stores[max_profit_index[0]]
max_profit_category = categories[max_profit_index[1]]
print("Maximum individual profit:")
print(f"Profit Amount: {max_profit}")
print(f"Store Name: {max_profit_store}")
print(f"Product Category: {max_profit_category}")

Maximum individual profit:
Profit Amount: 260000
Store Name: Mumbai
Product Category: Electronics


Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
import numpy as np
min_profit_index = np.unravel_index(np.argmin(profit_data), profit_data.shape)
min_profit = profit_data[min_profit_index]
min_profit_store = stores[min_profit_index[0]]
min_profit_category = categories[min_profit_index[1]]
print("Minimum individual profit:")
print(f"Profit Amount: {min_profit}")
print(f"Store Name: {min_profit_store}")
print(f"Product Category: {min_profit_category}")

Minimum individual profit:
Profit Amount: 55000
Store Name: Pune
Product Category: Furniture


Part 7: Profit Margin Analysis

Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100
Round the result to two decimal places.

In [ ]:
import numpy as np

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
print("Profit Margin Matrix:")
print(profit_margin)

Profit Margin Matrix:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

total_profit_per_store = np.sum(profit_data, axis=1)
total_sales_per_store = np.sum(sales_data, axis=1)
store_profit_margin = (total_profit_per_store / total_sales_per_store) * 100
for store, margin in zip(stores, store_profit_margin):
    print(f"Store: {store}, Profit Margin: {margin}%")

Store: Bengaluru, Profit Margin: 26.651982378854626%
Store: Hyderabad, Profit Margin: 26.57952069716776%
Store: Chennai, Profit Margin: 25.97402597402597%
Store: Mumbai, Profit Margin: 26.773049645390074%
Store: Pune, Profit Margin: 25.5050505050505%


Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [ ]:
import numpy as np

# Product categories
categories = np.array([
    "Electronics",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
total_profit_per_category = np.sum(profit_data, axis=0)
total_sales_per_category = np.sum(sales_data, axis=0)
category_profit_margin = (total_profit_per_category / total_sales_per_category) * 100
for category, margin in zip(categories, category_profit_margin):
    print(f"Category: {category}, Profit Margin: {margin}%")



Category: Electronics, Profit Margin: 24.242424242424242%
Category: Clothing, Profit Margin: 24.02745995423341%
Category: Furniture, Profit Margin: 28.4375%
Category: Beauty, Profit Margin: 26.148409893992934%
Category: Sports, Profit Margin: 34.15841584158416%


Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

total_profit_per_store = np.sum(profit_data, axis=1)
total_sales_per_store = np.sum(sales_data, axis=1)
store_profit_margin = (total_profit_per_store / total_sales_per_store)
best_store_index = np.argmax(store_profit_margin)
best_store = stores[best_store_index]
best_margin = store_profit_margin[best_store_index]
print("Best store by profit margin:")
print(f"Store: {best_store}, Profit Margin: {best_margin * 100}%")


Best store by profit margin:
Store: Mumbai, Profit Margin: 26.773049645390074%


Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [ ]:
import numpy as np

# Product categories
categories = np.array([
    "Electronics",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

total_profit_per_category = np.sum(profit_data, axis=0)
total_sales_per_category = np.sum(sales_data, axis=0)
category_profit_margin = (total_profit_per_category / total_sales_per_category)
best_category_index = np.argmax(category_profit_margin)
best_category = categories[best_category_index]
best_margin = category_profit_margin[best_category_index]
print("Best category by profit margin:")
print(f"Category: {best_category}, Profit Margin: {best_margin * 100}%")

Best category by profit margin:
Category: Sports, Profit Margin: 34.15841584158416%


Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [97]:
import numpy as np
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
low_margin_transactions = profit_margin < 22
print("Low Margin Transactions:")
print(low_margin_transactions)
rows, cols = np.where(low_margin_transactions)
print("\nStore:", stores[rows])
print("Category:", categories[cols])
print("Sales:", sales_data[rows, cols])
print("Cost:", cost_data[rows, cols])
print("Profit:", profit_data[rows, cols])
print("Profit Margin:", profit_margin[rows, cols])

Low Margin Transactions:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]

Store: []
Category: []
Sales: []
Cost: []
Profit: []
Profit Margin: []


Part 8: Boolean Filtering

Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [ ]:
import numpy as np
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [ ]:
import numpy as np
high_sales_values = sales_data[sales_data > 500000]
print("Sales values greater than ₹5,00,000:")
print(high_sales_values)

Sales values greater than ₹5,00,000:
[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [ ]:
import numpy as np

low_sales_values = sales_data[sales_data < 200000]
print("Sales values below ₹2,00,000:")
print(low_sales_values)



Sales values below ₹2,00,000:
[190000 185000 175000]


Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [ ]:
import numpy as np
profit_data = sales_data - cost_data
high_profit_values = profit_data[profit_data > 150000]
print("Profit Matrix:")
print(profit_data)



Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [ ]:
import numpy as np
moderate_sales_range = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]
print("Sales values between ₹2,50,000 and ₹5,00,000:")
print(moderate_sales_range)

Sales values between ₹2,50,000 and ₹5,00,000:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance

A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [ ]:
import numpy as np
premium_combinations = np.logical_and(sales_data > 500000, profit_data > 150000)
print("Premium-performing combinations:")
print(premium_combinations)

Premium-performing combinations:
[[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]]


Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [ ]:
import numpy as np
underperforming_combinations = np.logical_and(sales_data < 250000, profit_margin < 25)
print("Underperforming combinations:")
print(underperforming_combinations)

Underperforming combinations:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [ ]:
import numpy as np

category_classification = np.where(sales_data >= 500000, "High",
                                   np.where(np.logical_and(sales_data >= 250000, sales_data < 500000), "Medium", "Low"))
print("Category Classification:")
print(category_classification)

Category Classification:
[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison

Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.



In [ ]:
import numpy as np
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])


In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
print("Target Comparison:")
print(target_comparison)

Target Comparison:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 49: Target Achievement Matrix

Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
print("Target Achievement Matrix:")
print(target_achievement_matrix)


Target Achievement Matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
target_achievement_count = np.sum(target_achievement_matrix, axis=1)
print("Target Achievement Count:")
print(target_achievement_count)

Target Achievement Count:
[1 4 2 6 0]


Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
target_achievement_count = np.sum(target_achievement_matrix, axis=1)
best_store_index = np.argmax(target_achievement_count)
print("Best target-performing store:")
print(f"Store: {stores[best_store_index]}")

Best target-performing store:
Store: Mumbai


Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
target_achievement_count = np.sum(target_achievement_matrix, axis=0)
print("Target Achievement by Category:")
print(target_achievement_count)

Target Achievement by Category:
[3 2 2 2 2 2]


Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [ ]:
import numpy as np
variance = sales_data - sales_targets
print("Sales Target Variance:")
print(variance)

Sales Target Variance:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
import numpy as np
percentage_variance = (sales_data - sales_targets) / sales_targets * 100
print("Percentage Variance from Target:")
print(percentage_variance)

Percentage Variance from Target:
[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
stores_missing_electronics_target = np.where(target_achievement_matrix[:, 0] == False)
print("Stores missing Electronics target:")
print(stores[stores_missing_electronics_target])

Stores missing Electronics target:
['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use np.all()

In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
stores_achieving_all_targets = np.all(target_achievement_matrix, axis=1)
print("Stores achieving all targets:")
print(stores[stores_achieving_all_targets])

Stores achieving all targets:
['Mumbai']


Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use np.any().



In [ ]:
import numpy as np
target_comparison = sales_data - sales_targets
target_achievement_matrix = target_comparison >= 0
stores_achieving_at_least_one_target = np.any(target_achievement_matrix, axis=1)
print("Stores achieving at least one target:")
print(stores[stores_achieving_at_least_one_target])

Stores achieving at least one target:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

In [ ]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])


Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.



In [ ]:
import numpy as np
discount_amount = sales_data * discount_rates
print("Discount Amount Matrix:")
print(discount_amount)

Discount Amount Matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [ ]:
import numpy as np
net_sales = sales_data - discount_amount
print("Net Sales After Discount:")
print(net_sales)

Net Sales After Discount:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.



In [ ]:
import numpy as np
profit_after_discount = net_sales - cost_data
print("Profit After Discount:")
print(profit_after_discount)

Profit After Discount:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [ ]:
import numpy as np
profit_margin_after_discount = (profit_after_discount / net_sales) * 100
print("Profit Margin After Discount:")
print(profit_margin_after_discount)

Profit Margin After Discount:
[[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.



In [ ]:
import numpy as np
loss_making_transactions = profit_after_discount < 0
affected_stores = stores[np.where(loss_making_transactions[:, 0])]
affected_categories = categories[np.where(loss_making_transactions[0])]
print("Loss-making transactions:")
print(f"Stores: {affected_stores}")
print(f"Categories: {affected_categories}")

Loss-making transactions:
Stores: []
Categories: []


Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.



In [3]:
import numpy as np

discount_amount = sales_data * discount_rates
total_discount_loss = np.sum(discount_amount)
print("Total Discount Loss:")
print(total_discount_loss)

Total Discount Loss:
1146350.0


Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts

In [8]:
import numpy as np
discount_amount = sales_data * discount_rates
total_discount_loss = np.sum(discount_amount, axis=1)
most_affected_store_index = np.argmax(total_discount_loss)
most_affected_store = stores[most_affected_store_index]
print("Store most affected by discounts:")
print(most_affected_store)

Store most affected by discounts:
Mumbai


Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

In [9]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])


In [10]:
import numpy as np
tax_amount = sales_data * tax_rates
print("Tax Amount Matrix:")
print(tax_amount)

Tax Amount Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [11]:
import numpy as np
tax_collected = sales_data * tax_rates
print("Tax Collected Matrix:")
print(tax_collected)

Tax Collected Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.



In [12]:
import numpy as np
sales_including_tax = sales_data + tax_amount
print("Sales Including Tax:")
print(sales_including_tax)

Sales Including Tax:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [13]:
import numpy as np
total_tax_collected = np.sum(tax_collected, axis=1)
print("Total Tax Collected by Store:")
print(total_tax_collected)

Total Tax Collected by Store:
[321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [14]:
import numpy as np
total_tax_collected = np.sum(tax_collected, axis=0)
print("Total Tax Collected by Category:")
print(total_tax_collected)

Total Tax Collected by Category:
[772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [15]:
import numpy as np
total_tax_collected = np.sum(tax_collected, axis=1)
highest_tax_contributing_store_index = np.argmax(total_tax_collected)
highest_tax_contributing_store = stores[highest_tax_contributing_store_index]
print("Highest tax-contributing store:")
print(highest_tax_contributing_store)


Highest tax-contributing store:
Mumbai


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [16]:
import numpy as np
pune_electronics_sales = sales_data[1, 0]
sales_data_copy = sales_data.copy()
sales_data_copy[1, 0] = 740000
print("Updated Pune Electronics Sales:")
print(sales_data_copy)

Updated Pune Electronics Sales:
[[ 850000  420000  310000  275000  190000  225000]
 [ 740000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [20]:
import numpy as np
cost_data_copy = cost_data.copy()
cost_data_copy[:, 4] *= 0.92
print("Revised Beauty Cost:")
print(cost_data_copy)

Revised Beauty Cost:
[[640000. 315000. 220000. 205000. 115000. 160000.]
 [590000. 350000. 210000. 225000. 128800. 170000.]
 [700000. 295000. 245000. 195000. 110400. 155000.]
 [790000. 390000. 265000. 250000. 151800. 205000.]
 [530000. 310000. 205000. 170000. 105800. 145000.]]


Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.



In [21]:
import numpy as np
cost_data_copy = cost_data.copy()
cost_data_copy[:, 3] *= 1.12
print("Furniture Cost Increase:")
print(cost_data_copy)

Furniture Cost Increase:
[[640000. 315000. 220000. 229600. 125000. 160000.]
 [590000. 350000. 210000. 252000. 140000. 170000.]
 [700000. 295000. 245000. 218400. 120000. 155000.]
 [790000. 390000. 265000. 280000. 165000. 205000.]
 [530000. 310000. 205000. 190400. 115000. 145000.]]


Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().



In [22]:
import numpy as np
sales_data_copy = np.delete(sales_data, 1, axis=0)
cost_data_copy = np.delete(cost_data, 1, axis=0)
print("Store Closure Simulation:")
print("Sales Data:")
print(sales_data_copy)
print("Cost Data:")
print(cost_data_copy)

Store Closure Simulation:
Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Cost Data:
[[640000. 315000. 220000. 205000. 125000. 160000.]
 [700000. 295000. 245000. 195000. 120000. 155000.]
 [790000. 390000. 265000. 250000. 165000. 205000.]
 [530000. 310000. 205000. 170000. 115000. 145000.]]


Question 74: Adding a New Store

A new Delhi store is opened with the following data:



In [23]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [24]:
import numpy as np
sales_data_copy = np.vstack((sales_data, delhi_sales))
cost_data_copy = np.vstack((cost_data, delhi_cost))
stores_copy = np.append(stores, "Delhi")
print("Adding a New Store:")
print("Sales Data:")
print(sales_data_copy)
print("Cost Data:")
print(cost_data_copy)
print("Stores:")
print(stores_copy)

Adding a New Store:
Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Cost Data:
[[640000. 315000. 220000. 205000. 125000. 160000.]
 [590000. 350000. 210000. 225000. 140000. 170000.]
 [700000. 295000. 245000. 195000. 120000. 155000.]
 [790000. 390000. 265000. 250000. 165000. 205000.]
 [530000. 310000. 205000. 170000. 115000. 145000.]
 [665000. 360000. 235000. 215000. 145000. 180000.]]
Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

In [25]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

Add the new category as a column using np.column_stack() or np.hstack().



In [26]:
import numpy as np
sales_data_copy = np.column_stack((sales_data, home_appliance_sales))
cost_data_copy = np.column_stack((cost_data, home_appliance_cost))
print("Adding a New Product Category:")
print("Sales Data:")
print(sales_data_copy)
print("Cost Data:")
print(cost_data_copy)


Adding a New Product Category:
Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Cost Data:
[[640000. 315000. 220000. 205000. 125000. 160000. 265000.]
 [590000. 350000. 210000. 225000. 140000. 170000. 240000.]
 [700000. 295000. 245000. 195000. 120000. 155000. 285000.]
 [790000. 390000. 265000. 250000. 165000. 205000. 305000.]
 [530000. 310000. 205000. 170000. 115000. 145000. 225000.]]


Part 13: Sorting and Ranking

Question 76: Sort Stores by Sales


Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [27]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
sorted_indices = np.argsort(total_sales)
sorted_stores = stores[sorted_indices]
sorted_sales = total_sales[sorted_indices]
print("Sort Stores by Sales:")
for store, sales in zip(sorted_stores, sorted_sales):
    print(f"Store: {store}, Sales: {sales}")

Sort Stores by Sales:
Store: Pune, Sales: 1980000
Store: Bengaluru, Sales: 2270000
Store: Hyderabad, Sales: 2295000
Store: Chennai, Sales: 2310000
Store: Mumbai, Sales: 2820000


Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use np.argsort().

In [28]:
import numpy as np
profit = sales_data - cost_data
total_profit = np.sum(profit, axis=1)
sorted_indices = np.argsort(total_profit)[::-1]
ranked_stores = stores[sorted_indices]
print("Rank Stores by Profit:")
for rank, store in enumerate(ranked_stores, start=1):
    print(f"Rank {rank}: {store}")

Rank Stores by Profit:
Rank 1: Mumbai
Rank 2: Hyderabad
Rank 3: Bengaluru
Rank 4: Chennai
Rank 5: Pune


Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.



In [31]:
import numpy as np



total_revenue = np.sum(sales_data, axis=0)
sorted_indices = np.argsort(total_revenue)[::-1]
sorted_categories = categories[sorted_indices]
print("Sort Categories by Revenue:")
print(sorted_categories)

Sort Categories by Revenue:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Sports' 'Beauty']


Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [34]:
import numpy as np
flattened_sales = sales_data.flatten()
sorted_indices = np.argsort(flattened_sales)[::-1]
top_three_indices = sorted_indices[:3]
top_three_sales_values = flattened_sales[top_three_indices]
top_three_stores = stores[np.unravel_index(top_three_indices, sales_data.shape)[0]]
top_three_categories = categories[np.unravel_index(top_three_indices, sales_data.shape)[1]]
print("Top Three Store-Category Sales:")
for sales, store, category in zip(top_three_sales_values, top_three_stores, top_three_categories):
    print(f"Sales: {sales}, Store: {store}, Category: {category}")




Top Three Store-Category Sales:
Sales: 1050000, Store: Mumbai, Category: Electronics
Sales: 920000, Store: Chennai, Category: Electronics
Sales: 850000, Store: Bengaluru, Category: Electronics


Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [35]:
import numpy as np
flattened_profit = profit.flatten()
sorted_indices = np.argsort(flattened_profit)
bottom_three_indices = sorted_indices[:3]
bottom_three_profits = flattened_profit[bottom_three_indices]
print("Bottom Three Profits:")
print(bottom_three_profits)

Bottom Three Profits:
[55000. 60000. 60000.]


Part 14: Statistical Analysis

Question 81: Sales Statistics

Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [36]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_sales = np.std(sales_data)
var_sales = np.var(sales_data)
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)
print("Sales Statistics:")
print(f"Minimum: {min_sales}")
print(f"Maximum: {max_sales}")
print(f"Mean: {mean_sales}")
print(f"Median: {median_sales}")
print(f"Standard Deviation: {std_sales}")
print(f"Variance: {var_sales}")
print(f"25th Percentile: {percentile_25}")
print(f"50th Percentile: {percentile_50}")
print(f"75th Percentile: {percentile_75}")

Sales Statistics:
Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [37]:
import numpy as np
std_deviation = np.std(sales_data, axis=1)
max_std_index = np.argmax(std_deviation)
store_with_most_variation = stores[max_std_index]
print("Store-Wise Standard Deviation:")
print(std_deviation)
print(f"Store with the most variation: {store_with_most_variation}")

Store-Wise Standard Deviation:
[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Store with the most variation: Mumbai


Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [38]:
import numpy as np
std_deviation = np.std(sales_data, axis=0)
max_std_index = np.argmax(std_deviation)
category_with_highest_variation = categories[max_std_index]
print("Category-Wise Standard Deviation:")
print(std_deviation)
print(f"Category with the highest variation: {category_with_highest_variation}")


Category-Wise Standard Deviation:
[122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Category with the highest variation: Electronics


Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average

In [39]:
import numpy as np
company_average_sales = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_average_sales)
print("Sales Above Company Average:")
print(f"Company-wide average sales: {company_average_sales}")

Sales Above Company Average:
Company-wide average sales: 389166.6666666667


Question 85: Outlier Detection

Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [40]:
import numpy as np
threshold = np.mean(sales_data) + 1.5 * np.std(sales_data)
outliers = sales_data[sales_data > threshold]
print("Outlier Detection:")
print("High-value outliers:")
print(outliers)



Outlier Detection:
High-value outliers:
[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [41]:
import numpy as np
flattened_sales = sales_data.flatten()
print("Flatten Sales Data:")
print(flattened_sales)


Flatten Sales Data:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data

Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [42]:
import numpy as np
reshaped_3_10 = sales_data.reshape(3, 10)
reshaped_10_3 = sales_data.reshape(10, 3)
reshaped_2_15 = sales_data.reshape(2, 15)
reshaped_15_2 = sales_data.reshape(15,2)
print("Reshape Sales Data:")
print("3 × 10:")
print(reshaped_3_10)
print("10 × 3:")
print(reshaped_10_3)
print("2 × 15:")
print(reshaped_2_15)
print("15 × 2:")
print(reshaped_15_2)



Reshape Sales Data:
3 × 10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
10 × 3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
2 × 15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
15 × 2:
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]

Question 88: Transpose Sales Data

Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

In [43]:
import numpy as np
transposed_sales = np.transpose(sales_data)
print("Transposed Sales Data:")
print(transposed_sales)
print("New shape:", transposed_sales.shape)

Transposed Sales Data:
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape: (6, 5)


Question 89: Combined Sales and Cost Array

Stack sales_data and cost_data vertically.

Display the resulting shape.

In [44]:
import numpy as np
combined_data = np.vstack((sales_data, cost_data))
print("Combined Sales and Cost Array:")
print(combined_data)
print("Resulting shape:", combined_data.shape)

Combined Sales and Cost Array:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]
 [ 640000.  315000.  220000.  205000.  125000.  160000.]
 [ 590000.  350000.  210000.  225000.  140000.  170000.]
 [ 700000.  295000.  245000.  195000.  120000.  155000.]
 [ 790000.  390000.  265000.  250000.  165000.  205000.]
 [ 530000.  310000.  205000.  170000.  115000.  145000.]]
Resulting shape: (10, 6)


Question 90: Store-Level Combined Data

Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [45]:
import numpy as np
combined_data = np.stack((sales_data, cost_data), axis=0)
print("Store-Level Combined Data:")
print(combined_data)
print("Shape of the new array:", combined_data.shape)

Store-Level Combined Data:
[[[ 850000.  420000.  310000.  275000.  190000.  225000.]
  [ 780000.  460000.  295000.  310000.  210000.  240000.]
  [ 920000.  390000.  340000.  260000.  185000.  215000.]
  [1050000.  510000.  375000.  345000.  250000.  290000.]
  [ 690000.  405000.  280000.  225000.  175000.  205000.]]

 [[ 640000.  315000.  220000.  205000.  125000.  160000.]
  [ 590000.  350000.  210000.  225000.  140000.  170000.]
  [ 700000.  295000.  245000.  195000.  120000.  155000.]
  [ 790000.  390000.  265000.  250000.  165000.  205000.]
  [ 530000.  310000.  205000.  170000.  115000.  145000.]]]
Shape of the new array: (2, 5, 6)


Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

In [46]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [47]:
import numpy as np
missing_indices = np.isnan(sales_with_missing)
print("Missing Data Scenario:")
print("Missing values:")
print(missing_indices)

Missing Data Scenario:
Missing values:
[[False False  True False False False]
 [False False False  True False False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False  True False]]


Question 91: Missing Value Detection

Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [48]:
import numpy as np
missing_count = np.sum(np.isnan(sales_with_missing))
missing_indices = np.argwhere(np.isnan(sales_with_missing))
missing_stores = np.unique(missing_indices[:, 0])
missing_categories = np.unique(missing_indices[:, 1])
print("Missing Value Detection:")
print("Total number of missing values:", missing_count)
print("Location of missing values:")
print(missing_indices)
print("Stores containing missing values:", missing_stores)
print("Categories containing missing values:", missing_categories)


Missing Value Detection:
Total number of missing values: 4
Location of missing values:
[[0 2]
 [1 3]
 [3 1]
 [4 4]]
Stores containing missing values: [0 1 3 4]
Categories containing missing values: [1 2 3 4]


Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [49]:
import numpy as np
sales_with_missing[np.isnan(sales_with_missing)] = 0
print("Replace Missing Values with Zero:")
print(sales_with_missing)


Replace Missing Values with Zero:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use np.nanmean()

In [50]:
import numpy as np
company_average = np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = company_average
print("Replace with Company Average:")
print(sales_with_missing)

Replace with Company Average:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [53]:
import numpy as np
category_averages = np.nanmean(sales_with_missing, axis=0)
missing_rows, missing_cols = np.where(np.isnan(sales_with_missing))
sales_with_missing[missing_rows, missing_cols] = category_averages[missing_cols]
print("Replace with Category Average:")
print(sales_with_missing)



Replace with Category Average:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [54]:
import numpy as np
total_sales_before = np.sum(sales_data)
total_sales_after = np.sum(sales_with_missing)
print("Missing Value Impact:")
print("Total sales before replacing missing values:", total_sales_before)
print("Total sales after replacing missing values with zero:", total_sales_after)


Missing Value Impact:
Total sales before replacing missing values: 11675000
Total sales after replacing missing values with zero: 11596250.0


Part 17: Conditional Business Decisions

Question 96: Store Performance Labels

Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [55]:
import numpy as np
sales_labels = np.select(
    [sales_data.sum(axis=1) > 28000000,
     (sales_data.sum(axis=1) >= 24000000) & (sales_data.sum(axis=1) <= 28000000),
     sales_data.sum(axis=1) < 24000000],
    ['Excellent', 'Good', 'Needs Improvement'],
    default='Unknown'
)
print("Store Performance Labels:")
for store, label in zip(stores, sales_labels):
    print(f"Store: {store}, Performance: {label}")

Store Performance Labels:
Store: Bengaluru, Performance: Needs Improvement
Store: Hyderabad, Performance: Needs Improvement
Store: Chennai, Performance: Needs Improvement
Store: Mumbai, Performance: Needs Improvement
Store: Pune, Performance: Needs Improvement


Question 97: Profitability Classification

Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [56]:
import numpy as np
profit = sales_data - cost_data
profit_labels = np.select(
    [profit > 200000,
     (profit >= 100000) & (profit <= 200000),
     profit < 100000,
     profit < 0],
    ['Highly Profitable', 'Profitable', 'Low Profit', 'Loss'],
    default='Unknown'
)
print("Profitability Classification:")
for store, category, label in zip(stores, categories, profit_labels):
    print(f"Store: {store}, Category: {category}, Profitability: {label}")

Profitability Classification:
Store: Bengaluru, Category: Electronics, Profitability: ['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Store: Hyderabad, Category: Groceries, Profitability: ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Store: Chennai, Category: Clothing, Profitability: ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']
Store: Mumbai, Category: Furniture, Profitability: ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
 'Low Profit']
Store: Pune, Category: Beauty, Profitability: ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
 'Low Profit']


Question 98: Expansion Recommendation

A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [57]:
import numpy as np
sales_above_threshold = np.sum(sales_data, axis=1) > 25000000
profit_above_threshold = np.sum(profit, axis=1) > 7000000
overall_profit_margin = np.mean(profit) / np.mean(sales_data) > 0.25
eligible_stores = np.where(sales_above_threshold & profit_above_threshold & overall_profit_margin)[0]
print("Expansion Recommendation:")
print("Eligible stores for expansion:")
print(eligible_stores)

Expansion Recommendation:
Eligible stores for expansion:
[]


Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [58]:
import numpy as np
average_sales = np.mean(sales_data, axis=0)
profit_margin = np.mean(profit, axis=0) / np.mean(sales_data, axis=0)
below_threshold_sales = average_sales < 300000
above_threshold_profit_margin = profit_margin > 0.25
eligible_categories = np.where(below_threshold_sales & above_threshold_profit_margin)[0]
print("Category Promotion Recommendation:")
print("Eligible categories for promotion:")
print(eligible_categories)

Category Promotion Recommendation:
Eligible categories for promotion:
[3 4 5]


Question 100: Cost Optimization Recommendation

Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [59]:
import numpy as np
cost_above_threshold = cost_data > 250000
profit_margin = np.mean(profit, axis=0) / np.mean(sales_data, axis=0)
below_threshold_profit_margin = profit_margin < 0.25
eligible_combinations = np.where(cost_above_threshold & below_threshold_profit_margin)
print("Cost Optimization Recommendation:")
print("Eligible combinations for cost optimization:")
print(eligible_combinations)

Cost Optimization Recommendation:
Eligible combinations for cost optimization:
(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4]), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))


Part 18: Inventory Scenario

Use the following inventory arrays:

In [61]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
print(opening_stock)
print(units_sold)

[[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


In [62]:
import numpy as np
closing_stock = opening_stock - units_sold
print("Inventory Scenario:")
print("Closing stock:")
print(closing_stock)

Inventory Scenario:
Closing stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 101: Closing Stock

Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [63]:
import numpy as np
closing_stock = opening_stock - units_sold
print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

In [64]:
import numpy as np
low_stock_indices = np.where(closing_stock < 30)
low_stock_stores = np.unique(low_stock_indices[0])
low_stock_categories = np.unique(low_stock_indices[1])
print("Low-Stock Identification:")
print("Stores with low stock:")
print(low_stock_stores)
print("Categories with low stock:")
print(low_stock_categories)


Low-Stock Identification:
Stores with low stock:
[0 1 2 3 4]
Categories with low stock:
[0 3]


Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [65]:
import numpy as np
unsold_percentage = (np.sum(opening_stock) - np.sum(units_sold)) / np.sum(opening_stock)
print("Stock Availability Percentage:")
print(f"{unsold_percentage * 100:.2f}%")


Stock Availability Percentage:
19.66%


Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [69]:
import numpy as np
sales_ratio = units_sold / opening_stock
fast_moving_mask = sales_ratio > 0.8
fast_moving_indices_2d = np.where(fast_moving_mask)
fast_moving_stores_indices = np.unique(fast_moving_indices_2d[0])
fast_moving_stores_names = stores[fast_moving_stores_indices]
fast_moving_categories_indices = np.unique(fast_moving_indices_2d[1])
fast_moving_categories_names = categories[fast_moving_categories_indices]
print("Fast-Moving Products:")
print("Stores with fast-moving products:")
print(fast_moving_stores_names)
print("Categories with fast-moving products:")
print(fast_moving_categories_names)





Fast-Moving Products:
Stores with fast-moving products:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
Categories with fast-moving products:
['Electronics' 'Groceries' 'Clothing']


Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.



In [70]:
import numpy as np
category_units_sold = np.sum(units_sold, axis=0)
print("Category-Wise Units Sold:")
print(category_units_sold)

Category-Wise Units Sold:
[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [71]:
import numpy as np
store_units_sold = np.sum(units_sold, axis=1)
print("Store-Wise Units Sold:")
print(store_units_sold)

Store-Wise Units Sold:
[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [72]:
import numpy as np
best_store_index = np.argmax(store_units_sold)
best_store_name = stores[best_store_index]
print("Best Store by Unit Sales:")
print(f"Store: {best_store_name}, Total units sold: {store_units_sold[best_store_index]}")


Best Store by Unit Sales:
Store: Mumbai, Total units sold: 1390


Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.



In [73]:
import numpy as np
reorder_matrix = closing_stock < 25
print("Reorder Requirement:")
print(reorder_matrix)

Reorder Requirement:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [74]:
import numpy as np
reorder_quantities = np.where(closing_stock < 25, 100 - closing_stock, 0)
print("Reorder Quantity:")
print(reorder_quantities)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using np.cumsum().



In [75]:
import numpy as np
cumulative_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Store Sales:")
print(cumulative_sales)

Cumulative Store Sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [76]:
import numpy as np
flattened_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flattened_sales)
print("Cumulative Company Sales:")
print(cumulative_company_sales)

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using np.diff().

In [77]:
import numpy as np
sales_differences = np.diff(sales_data, axis=1)
print("Sales Difference Between Categories:")
print(sales_differences)

Sales Difference Between Categories:
[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values

Find all unique sales values in sales_data.

Also count the frequency of each value.

In [78]:
import numpy as np
unique_sales, counts = np.unique(sales_data, return_counts=True)
print("Unique Sales Values:")
print(unique_sales)
print("Frequency of each value:")
print(counts)

Unique Sales Values:
[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequency of each value:
[1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [79]:
import numpy as np
value_to_search = 420000
location = np.where(sales_data == value_to_search)
print("Search for Specific Sales:")
print(f"Value {value_to_search} exists at location: {location}")

Search for Specific Sales:
Value 420000 exists at location: (array([0]), array([1]))


Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all()

In [80]:
import numpy as np
profitable_combinations = sales_data > cost_data
all_profitable = np.all(profitable_combinations)
print("Compare Sales and Cost:")
print("Profitable Combinations:")
print(profitable_combinations)
print("All combinations are profitable:", all_profitable)


Compare Sales and Cost:
Profitable Combinations:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All combinations are profitable: True


Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [81]:
import numpy as np
min_profit = 75000
max_profit = 250000
reporting_profit = np.clip(profit, min_profit, max_profit)
print("Clip Profit Values:")
print("Reporting profit array:")
print(reporting_profit)

Clip Profit Values:
Reporting profit array:
[[210000. 105000.  90000.  75000.  75000.  75000.]
 [190000. 110000.  85000.  85000.  75000.  75000.]
 [220000.  95000.  95000.  75000.  75000.  75000.]
 [250000. 120000. 110000.  95000.  85000.  85000.]
 [160000.  95000.  75000.  75000.  75000.  75000.]]


Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)


In [82]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("Normalize Sales Data:")
print("Normalized sales array:")
print(normalized_sales)

Normalize Sales Data:
Normalized sales array:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation


In [83]:
import numpy as np
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print("Standardize Sales Data:")
print("Standardized sales array:")
print(standardized_sales)

Standardize Sales Data:
Standardized sales array:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values

Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [84]:
import numpy as np
profit_margin = np.mean(profit, axis=0) / np.mean(sales_data, axis=0)
print("Round Values:")
print("Original profit margin array:")
print(profit_margin)
print("Two decimal places:")
print(np.round(profit_margin, 2))
print("Nearest whole number:")
print(np.round(profit_margin))
print("Floor values:")
print(np.floor(profit_margin))
print("Ceiling values:")
print(np.ceil(profit_margin))


Round Values:
Original profit margin array:
[0.24242424 0.2402746  0.284375   0.2614841  0.34158416 0.2893617 ]
Two decimal places:
[0.24 0.24 0.28 0.26 0.34 0.29]
Nearest whole number:
[0. 0. 0. 0. 0. 0.]
Floor values:
[0. 0. 0. 0. 0. 0.]
Ceiling values:
[1. 1. 1. 1. 1. 1.]


Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [87]:
import numpy as np

profit_data = sales_data - cost_data

np.save('sales_data.npy', sales_data)
np.save('cost_data.npy', cost_data)
np.save('profit_data.npy', profit_data)

loaded_sales_data = np.load('sales_data.npy')
loaded_cost_data = np.load('cost_data.npy')
loaded_profit_data = np.load('profit_data.npy')

print("Original sales data:")
print(sales_data)
print("Loaded sales data:")
print(loaded_sales_data)

print("Original cost data:")
print(cost_data)
print("Loaded cost data:")
print(loaded_cost_data)

print("Original profit data:")
print(profit_data)
print("Loaded profit data:")
print(loaded_profit_data)


Original sales data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Loaded sales data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Original cost data:
[[640000. 315000. 220000. 205000. 125000. 160000.]
 [590000. 350000. 210000. 225000. 140000. 170000.]
 [700000. 295000. 245000. 195000. 120000. 155000.]
 [790000. 390000. 265000. 250000. 165000. 205000.]
 [530000. 310000. 205000. 170000. 115000. 145000.]]
Loaded cost data:
[[640000. 315000. 220000. 205000. 125000. 160000.]
 [590000. 350000. 210000. 225000. 140000. 170000.]
 [700000. 295000. 245000. 195000. 120000. 155000.]
 

Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder


In [89]:
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
overall_profit_margin = np.mean(profit / total_sales)
average_transaction_value = np.mean(total_sales)
highest_individual_sales_value = np.max(total_sales)
lowest_individual_sales_value = np.min(total_sales)
total_sales_by_store = np.sum(sales_data, axis=0)
total_cost_by_store = np.sum(cost_data, axis=0)
total_profit_by_store = total_sales_by_store - total_cost_by_store
profit_margin_by_store = total_profit_by_store / total_sales_by_store
number_of_category_targets_achieved = np.sum(sales_data >= 400000, axis=0)
total_units_sold_by_store = np.sum(sales_data, axis=1)
expansion_eligibility_by_store = total_units_sold_by_store >= 5
total_sales_by_category = np.sum(sales_data, axis=1)
total_cost_by_category = np.sum(cost_data, axis=1)
total_profit_by_category = total_sales_by_category - total_cost_by_category
profit_margin_by_category = total_profit_by_category / total_sales_by_category
average_sales_by_category = np.mean(sales_data, axis=0)
number_of_stores_achieving_target = np.sum(sales_data >= 400000, axis=1)
total_units_sold_by_category = np.sum(sales_data, axis=0)
best_performing_store_index = np.argmax(total_sales_by_store)
lowest_performing_store_index = np.argmin(total_sales_by_store)
most_profitable_category_index = np.argmax(total_profit_by_category)
lowest_profitable_category_index = np.argmin(total_profit_by_category)
store_recommended_for_expansion_index = np.argmax(expansion_eligibility_by_store)
category_requiring_additional_marketing_index = np.argmax(number_of_stores_achieving_target)
store_category_combinations_requiring_cost_optimization_indices = np.where(sales_data < 400000)
store_category_combinations_requiring_inventory_reorder_indices = np.where(sales_data < 300000)
print("Company Summary")
print("Total sales: ", total_sales)
print("Total cost: ", total_cost)
print("Total profit: ", profit)
print("Overall profit margin: ", overall_profit_margin)
print("Average transaction value: ", average_transaction_value)
print("Highest individual sales value: ", highest_individual_sales_value)
print("Lowest individual sales value: ", lowest_individual_sales_value)
print("Store Summary")
print("Total sales of Store: ", total_sales_by_store)
print("Total cost of Store: ", total_cost_by_store)
print("Total profit of Store: ", total_profit_by_store)
print("Profit margin of Store: ", profit_margin_by_store)
print("Number of category targets achieved: ", number_of_category_targets_achieved)
print("Total units sold by Store: ", total_units_sold_by_store)
print("Expansion eligibility of Store: ", expansion_eligibility_by_store)
print("Category saummary")
print("Total sales of Category: ", total_sales_by_category)
print("Total cost of Category: ", total_cost_by_category)
print("Total profit of Category: ", total_profit_by_category)
print("Profit margin of Category: ", profit_margin_by_category)
print("Average sales of Category: ", average_sales_by_category)
print("Number of stores achieving target: ", number_of_stores_achieving_target)
print("Total units sold by Category: ", total_units_sold_by_category)
print("Management Recommendations")
print("Best performing store: ", stores[best_performing_store_index])
print("Lowest performing store: ", stores[lowest_performing_store_index])
print("Most profitable category: ", categories[most_profitable_category_index])
print("Lowest profitable category: ", categories[lowest_profitable_category_index])
print("Store recommended for expansion: ", stores[store_recommended_for_expansion_index])
print("Category requiring additional marketing: ", categories[category_requiring_additional_marketing_index])
print("Store-category combinations requiring cost optimization: ", store_category_combinations_requiring_cost_optimization_indices)
print("Store-category combinations requiring inventory reorder: ", store_category_combinations_requiring_inventory_reorder_indices)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("==================================")
print("COMPANY SUMMARY")
print("---------------")
print("Total Sales          : ", total_sales)
print("Total Cost           : ", total_cost)
print("Total Profit         : ", profit)
print("Overall Profit Margin: ", overall_profit_margin)
print()
print("BEST-PERFORMING STORE")
print("--------------------")
print("Store        : ", stores[best_performing_store_index])
print("Sales        : ", total_sales_by_store[best_performing_store_index])
print("Cost         : ", total_cost_by_store[best_performing_store_index])
print("Profit       : ", total_profit_by_store[best_performing_store_index])
print("Profit Margin: ", profit_margin_by_store[best_performing_store_index])
print()
print("MOST PROFITABLE CATEGORY")
print("-----------------------")
print("Category     : ", categories[most_profitable_category_index])
print("Sales        : ", total_sales_by_category[most_profitable_category_index])
print("Cost         : ", total_cost_by_category[most_profitable_category_index])
print("Profit       : ", total_profit_by_category[most_profitable_category_index])
print("Profit Margin: ", profit_margin_by_category[most_profitable_category_index])
print("EXPANSION RECOMMENDATIONS")
print("------------------------")
print("Eligible Stores: ", stores[expansion_eligibility_by_store])
print()
print("COST OPTIMIZATION")
print("----------------")
print("Store        : ", stores[store_category_combinations_requiring_cost_optimization_indices[0]])
print("Category     : ", categories[store_category_combinations_requiring_cost_optimization_indices[1]])
print("Cost         : ", cost_data[store_category_combinations_requiring_cost_optimization_indices[0], store_category_combinations_requiring_cost_optimization_indices[1]])
print("Profit Margin: ", profit_margin_by_category[store_category_combinations_requiring_cost_optimization_indices[0]])
print()
print("INVENTORY REORDER")
print("----------------")
print("Store           : ", stores[store_category_combinations_requiring_inventory_reorder_indices[0]])
print("Category        : ", categories[store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Closing Stock   : ", sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Reorder Quantity: ", 100 - sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])

Company Summary
Total sales:  [2270000 2295000 2310000 2820000 1980000]
Total cost:  [1665000 1685000 1710000 2065000 1475000]
Total profit:  [605000 610000 600000 755000 505000]
Overall profit margin:  0.26296725840097784
Average transaction value:  2335000.0
Highest individual sales value:  2820000
Lowest individual sales value:  1980000
Store Summary
Total sales of Store:  [4290000 2185000 1600000 1415000 1010000 1175000]
Total cost of Store:  [3250000 1660000 1145000 1045000  665000  835000]
Total profit of Store:  [1040000  525000  455000  370000  345000  340000]
Profit margin of Store:  [0.24242424 0.2402746  0.284375   0.2614841  0.34158416 0.2893617 ]
Number of category targets achieved:  [5 4 0 0 0 0]
Total units sold by Store:  [2270000 2295000 2310000 2820000 1980000]
Expansion eligibility of Store:  [ True  True  True  True  True]
Category saummary
Total sales of Category:  [2270000 2295000 2310000 2820000 1980000]
Total cost of Category:  [1665000 1685000 1710000 2065000 1